In [1]:
import pandas as pd

### Import

In [2]:
kaggle = pd.read_csv("../datasets/raw/movies_kaggle/kaggle_processed.csv", index_col=0)
tmdb = pd.read_csv("../datasets/raw/tmdb/tmdb_processed.csv", index_col=0)
netflix = pd.read_csv("../datasets/raw/netflix/netflix_processed.csv", index_col=0)

C:\Users\mpere\AppData\Local\Temp\ipykernel_4148\1015027298.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  kaggle = pd.read_csv("../datasets/raw/movies_kaggle/kaggle_processed.csv", index_col=0)

### Data Acknowledge

In [3]:
print(kaggle.shape)
kaggle.head()

(45466, 19)

,adult,belongs_to_collection,budget,genres,tmdb_id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,title,vote_average
0,False,toy story collection,30000000,"['animation', 'comedy', 'family']",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,['pixar_animation_studios'],['us'],1995-10-30,373554033.0,81.0,['en'],Toy Story,7.7
1,False,[],65000000,"['adventure', 'fantasy', 'family']",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"['tristar_pictures', 'teitler_film', 'intersco...",['us'],1995-12-15,262797249.0,104.0,"['en', 'fr']",Jumanji,6.9
2,False,grumpy old men collection,0,"['romance', 'comedy']",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"['warner_bros.', 'lancaster_gate']",['us'],1995-12-22,0.0,101.0,['en'],Grumpier Old Men,6.5
3,False,[],16000000,"['comedy', 'drama', 'romance']",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,['twentieth_century_fox_film_corporation'],['us'],1995-12-22,81452156.0,127.0,['en'],Waiting to Exhale,6.1
4,False,father of the bride collection,0,['comedy'],11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"['sandollar_productions', 'touchstone_pictures']",['us'],1995-02-10,76578911.0,106.0,['en'],Father of the Bride Part II,5.7

In [4]:
print(tmdb.shape)
tmdb.head()

(4803, 15)

,budget,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,title,vote_average
0,237000000,"['action', 'adventure', 'fantasy', 'science_fi...",19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"['ingenious_film_partners', 'twentieth_century...","['us', 'gb']",2009-12-10,2787965087,162.0,"['en', 'es']",Avatar,7.2
1,300000000,"['adventure', 'fantasy', 'action']",285,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"['walt_disney_pictures', 'jerry_bruckheimer_fi...",['us'],2007-05-19,961000000,169.0,['en'],Pirates of the Caribbean: At World's End,6.9
2,245000000,"['action', 'adventure', 'crime']",206647,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"['columbia_pictures', 'danjaq', 'b24']","['gb', 'us']",2015-10-26,880674609,148.0,"['fr', 'en', 'es', 'it', 'de']",Spectre,6.3
3,250000000,"['action', 'crime', 'drama', 'thriller']",49026,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"['legendary_pictures', 'warner_bros.', 'dc_ent...",['us'],2012-07-16,1084939099,165.0,['en'],The Dark Knight Rises,7.6
4,260000000,"['action', 'adventure', 'science_fiction']",49529,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,['walt_disney_pictures'],['us'],2012-03-07,284139100,132.0,['en'],John Carter,6.1

In [6]:
print(netflix.shape)
netflix.head()

(6865, 6)

,IMDb Score,Netflix Link,IMDb Link,Poster,TMDb Trailer,IMDb id
1,5.8,https://www.netflix.com/watch/81041267,https://www.imdb.com/title/tt4193072,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,tt4193072
2,7.4,https://www.netflix.com/watch/81306155,https://www.imdb.com/title/tt13393728,https://m.media-amazon.com/images/M/MV5BODAzOG...,https://www.youtube.com/watch?v=md3CmFLGK6Y,tt13393728
4,6.7,https://www.netflix.com/watch/81382068,https://www.imdb.com/title/tt0041155,https://m.media-amazon.com/images/M/MV5BMjVmMz...,https://www.youtube.com/watch?v=H0itWKFwMpQ,tt0041155
5,6.6,https://www.netflix.com/watch/81382187,https://www.imdb.com/title/tt0090115,https://m.media-amazon.com/images/M/MV5BZDY2NG...,https://www.youtube.com/watch?v=tjWouBLwe3c,tt0090115
6,6.2,https://www.netflix.com/watch/81382078,https://www.imdb.com/title/tt0435670,https://m.media-amazon.com/images/M/MV5BNjQ3Mj...,https://www.youtube.com/watch?v=yDB3Ha3vxyc,tt0435670

### Left join on Kaggle dataset

#### Manter apenas o dataset do kaggle

In [7]:
kaggle.to_csv("../datasets/movies_dataset.csv", index=False)